### ISSUE TITLE
No se estan interpretando las entidades html en los titulos de las fotos

### ISSUE THREAD

**Issue by jespino** [JaimeObregon/retrosantander#3]
Buenas, he encontrado un pequeño bug, no se estan interpretando las entidades html (`&quot;`) en este caso, en el titulo de las imagenes.

El problem parece estar en que se hace un reemplazo de innerText en lugar de innerHtml (lo cual tiene sentido para evitar tener que sanitizar), pero estaría bien reemplazar las entidades html durante el importado, para que funcionen con el innerText.

Adjunto captura:

![imagen](https://user-images.githubusercontent.com/290303/169839017-a90dedcc-a553-42d7-8ba3-68bc56648ea4.png)

**Comment by jespino** [comment]
Ok, parece que ya esta corregido en main. Pero faltaría desplegarlo en la ultima version.

**Comment by JaimeObregon** [comment]
Gracias, @jespino. Como bien apuntas, esto quedó resuelto hace algunos días, al mezclar #2. Quizá lo mezclé pero no desplegué el cambio en Retrogipuzcoa, y por ello te has topado nuevamente con ello. Sea como fuere ya está corregido y desplegado. Muchas gracias 🙂.
