### ISSUE TITLE
El ejemplo de uso del script de importacion no funciona

### ISSUE THREAD

**Issue by jespino** [JaimeObregon/retrosantander#4]
El ejemplo de uso del script de importacion no funciona porque sigue aputando al CDIS de Santander. Estaría bien contar con un ejemplo bueno para poder reproducir los pasos y dejar el sistema funcionando en local, de modo que se pueda contribuir mas facilmente.

**Comment by jespino** [comment]
Pensaba que el script era tambien para retrogipuzkoa, pero supongo que eso se obtiene usando otros medios.

**Comment by JaimeObregon** [comment]
Hola, @jespino. Sí; los datos de Guipúzcoa los estoy obteniendo con otro script diferente al de Santander. Quiero cargarlo al repositorio también; confío en poder hacerlo pronto. Gracias por tu comentario.
